#!/usr/bin/env node
const http = require("http");
const https = require("https");
const fs = require("fs");
const path = require("path");
const { exec } = require("child_process");
const { generateSwaggerServices } = require("./generateSwaggerXxxService.cjs");

const DEFAULT_OPTIONS = {
	hostname: "localhost",
	port: 8123,
	path: "/for-local/get-swagger",
	method: "GET",
	headers: {
		Accept: "text/event-stream",
	},
	serviceDir: "./src/handler/service",
	swaggerFile: "./swagger.json",
	typesDir: "./src/handler/service/@types",
	typesFile: "./src/handler/service/@types/ApiTypes.d.ts",
	unionArraysFile: "./src/handler/service/apiUnionArrays.ts",
	commonServiceFile: "./src/handler/service/commonService.ts",
	reconnectDelayMs: 10000,
	openApiTypescriptCommand: null,
	generateServices: true,
	generateUnionArraysFile: true,
	keepAlive: true,	
	log: console,
};

function mergeOptions(options = {}) {
	return {
		...DEFAULT_OPTIONS,
		...options,
		headers: {
			...DEFAULT_OPTIONS.headers,
			...(options.headers || {}),
		},
	};
}

function ensureDirSync(dirPath) {
	if (!fs.existsSync(dirPath)) {
		fs.mkdirSync(dirPath, { recursive: true });
	}
}

function generateTypes(options, onSuccess = () => {}) {
	const command =
		options.openApiTypescriptCommand ||
		`npx openapi-typescript ${options.swaggerFile} --output ${options.typesFile}`;

	options.log.log?.("Running openapi-typescript...");
	exec(command, (err, stdout, stderr) => {
		if (err) {
			options.log.error?.("Failed to generate TypeScript types:", err.message);
			return;
		}
		if (stdout) {
			options.log.log?.(stdout);
		}
		if (stderr) {
			options.log.error?.("openapi-typescript stderr:", stderr);
		}
		options.log.log?.("TypeScript types generated successfully.");
		onSuccess();
	});
}

function generateUnionArrays(swaggerData, options) {
	options.log.log?.("Generating union arrays file...");
	try {
		const schemas = swaggerData?.components?.schemas;
		if (!schemas) {
			options.log.log?.("No schemas found in swagger JSON.");
			return;
		}

		let fileContent = `// This file is auto-generated by typed-rx-http auto-node-script. Do not edit.\n\n`;
		fileContent += `import type { components } from './@types/ApiTypes';\n\n`;

		for (const schemaName in schemas) {
			const properties = schemas[schemaName]?.properties;
			if (!properties) continue;

			for (const propName in properties) {
				const propDetails = properties[propName];
				if (propDetails?.enum && Array.isArray(propDetails.enum)) {
					const variableName = `${schemaName}_${propName}`;
					const typeName = `components['schemas']['${schemaName}']['${propName}']`;
					const arrayString = JSON.stringify(propDetails.enum);
					fileContent += `export const ${variableName}: readonly ${typeName}[] = ${arrayString} as const;\n`;
				}
			}
		}

		ensureDirSync(path.dirname(options.unionArraysFile));
		fs.writeFileSync(options.unionArraysFile, fileContent, "utf8");
		options.log.log?.("Union arrays file generated successfully.");
	} catch (err) {
		options.log.error?.("Failed to generate union arrays file:", err.message);
	}
}

function parseServerSentEvent(event, log = console) {
	const lines = event.split("\n");
	let data = "";

	lines.forEach((line) => {
		if (line.startsWith("data:")) {
			data += line.slice(5).trim();
		}
	});

	if (!data) {
		return null;
	}

	try {
		return JSON.parse(data);
	} catch (err) {
		log.error?.("Failed to parse JSON data:", err.message, "\nRaw Data:", data);
		return null;
	}
}


function parseJsonResponseText(text, log = console) {
	try {
		return JSON.parse(text);
	} catch (err) {
		log.error?.("Failed to parse JSON response:", err.message, "\nRaw Data:", text);
		return null;
	}
}

function createRequestOptions(options, headersOverride = {}) {
	return {
		hostname: options.hostname,
		port: options.port,
		path: options.path,
		method: options.method,
		headers: {
			...options.headers,
			...headersOverride,
		},
	};
}

function requestJsonOnce(rawOptions = {}) {
	const options = mergeOptions(rawOptions);
	const requestLib = options.protocol === "https:" || options.https ? https : http;

	return new Promise((resolve, reject) => {
		const req = requestLib.request(
			createRequestOptions(options, { Accept: "application/json" }),
			(res) => {
				let body = "";
				res.setEncoding("utf8");
				res.on("data", (chunk) => {
					body += chunk;
				});
				res.on("end", () => {
					if (res.statusCode < 200 || res.statusCode >= 300) {
						reject(new Error(`HTTP ${res.statusCode}: ${body}`));
						return;
					}

					const parsed = parseJsonResponseText(body, options.log);
					if (!parsed) {
						reject(new Error("Failed to parse JSON response."));
						return;
					}

					resolve(parsed);
				});
			},
		);

		req.on("error", reject);
		req.end();
	});
}

async function generateSwaggerFromHttp(rawOptions = {}) {
	const options = mergeOptions(rawOptions);
	options.log.log?.("Requesting Swagger JSON once...");
	const swaggerData = await requestJsonOnce(options);
	handleSwaggerData(swaggerData, options);
	return swaggerData;
}

function generateSwaggerFromFile(rawOptions = {}) {
	const options = mergeOptions(rawOptions);
	const inputFile = options.inputFile || options.swaggerFile;
	options.log.log?.(`Reading Swagger JSON from ${inputFile}...`);
	const swaggerData = JSON.parse(fs.readFileSync(inputFile, "utf8"));
	handleSwaggerData(swaggerData, options);
	return swaggerData;
}

function handleSwaggerData(swaggerData, rawOptions = {}) {
	const options = mergeOptions(rawOptions);
	ensureDirSync(options.typesDir);
	ensureDirSync(options.serviceDir);
	ensureDirSync(path.dirname(options.swaggerFile));

	fs.writeFileSync(options.swaggerFile, JSON.stringify(swaggerData, null, 2), "utf8");
	options.log.log?.("Swagger JSON saved successfully.");

	generateTypes(options, () => {
		if (options.generateUnionArraysFile) {
			generateUnionArrays(swaggerData, options);
		}

		if (options.generateServices) {
			generateSwaggerServices({
				swaggerData,
				serviceDir: options.serviceDir,
				typesDir: options.typesDir,
				typesFile: options.typesFile,
				commonServiceFile: options.commonServiceFile,
				log: options.log,
			});
		}
	});
}

function connectToSwaggerEventStream(rawOptions = {}) {
	const options = mergeOptions(rawOptions);
	ensureDirSync(options.typesDir);
	ensureDirSync(options.serviceDir);

	let eventBuffer = "";
	let reconnectTimeout = null;
	let req = null;

	function scheduleReconnect() {
		if (reconnectTimeout) {
			return;
		}
		options.log.log?.(`Scheduling reconnect in ${options.reconnectDelayMs / 1000} seconds...`);
		reconnectTimeout = setTimeout(() => {
			reconnectTimeout = null;
			connect();
		}, options.reconnectDelayMs);
	}

	function connect() {
		options.log.log?.("Attempting to connect to Swagger EventStream...");

		req = http.request(
			createRequestOptions(options),
			(res) => {
				if (res.statusCode !== 200) {
					options.log.error?.(`Failed to connect: ${res.statusCode}`);
					scheduleReconnect();
					return;
				}

				options.log.log?.("Connected to Swagger EventStream.");
				eventBuffer = "";
				res.setEncoding("utf8");

				res.on("data", (chunk) => {
					eventBuffer += chunk;
					let boundary = eventBuffer.indexOf("\n\n");
					while (boundary !== -1) {
						const event = eventBuffer.slice(0, boundary);
						eventBuffer = eventBuffer.slice(boundary + 2);

						const parsedData = parseServerSentEvent(event, options.log);
						if (parsedData) {
							options.log.log?.("Received updated Swagger JSON.");
							try {
								handleSwaggerData(parsedData, options);
							} catch (err) {
								options.log.error?.("Failed to process Swagger JSON:", err.message);
							}
						}

						boundary = eventBuffer.indexOf("\n\n");
					}
				});

				res.on("end", () => {
					options.log.log?.("Swagger EventStream connection closed by server.");
					scheduleReconnect();
				});
				res.on("close", () => {
					options.log.log?.("Swagger EventStream connection closed.");
					scheduleReconnect();
				});
				res.on("error", (err) => {
					options.log.error?.("Stream error:", err.message);
					scheduleReconnect();
				});
			},
		);

		req.on("error", (err) => {
			options.log.error?.("Connection error:", err.message);
			scheduleReconnect();
		});

		req.end();
	}

	connect();

	let keepAliveTimer = null;
	if (options.keepAlive) {
		keepAliveTimer = setInterval(() => {}, 1000);
	}

	return {
		close() {
			if (reconnectTimeout) {
				clearTimeout(reconnectTimeout);
				reconnectTimeout = null;
			}
			if (keepAliveTimer) {
				clearInterval(keepAliveTimer);
				keepAliveTimer = null;
			}
			req?.destroy?.();
		},
	};
}

if (require.main === module) {
	const mode = process.argv.includes("--http") ? "http" : process.argv.includes("--file") ? "file" : "event-stream";
	if (mode === "http") {
		generateSwaggerFromHttp().catch((err) => {
			console.error(err);
			process.exit(1);
		});
	} else if (mode === "file") {
		try {
			generateSwaggerFromFile();
		} catch (err) {
			console.error(err);
			process.exit(1);
		}
	} else {
		connectToSwaggerEventStream();
	}
	process.on("SIGINT", () => process.exit());
	process.on("SIGTERM", () => process.exit());
	process.on("uncaughtException", (err) => {
		console.error("Uncaught exception:", err);
		process.exit(1);
	});
}

module.exports = {
	DEFAULT_OPTIONS,
	mergeOptions,
	parseServerSentEvent,
	parseJsonResponseText,
	requestJsonOnce,
	generateSwaggerFromHttp,
	generateSwaggerFromFile,
	generateTypes,
	generateUnionArrays,
	handleSwaggerData,
	connectToSwaggerEventStream,
	generateSwaggerServices,
};
