const fs = require("fs");
const path = require("path");

const AUTO_GENERATED_COMMENT =
	"// This file is auto-generated by generateSwaggerXxxService.js. Do not edit.\n";

function ensureDirSync(dirPath) {
	if (!fs.existsSync(dirPath)) {
		fs.mkdirSync(dirPath, { recursive: true });
	}
}

function stripExtension(fileName) {
	return fileName.replace(/\.d\.ts$/i, "").replace(/\.ts$/i, "");
}

function normalizeImportPath(filePath) {
	let normalized = filePath.replace(/\\/g, "/");
	if (!normalized.startsWith(".")) {
		normalized = "./" + normalized;
	}
	return normalized;
}

function getRelativeImportPath(fromFilePath, toFilePath) {
	const fromDir = path.dirname(fromFilePath);
	const rel = path.relative(fromDir, toFilePath);
	return normalizeImportPath(stripExtension(rel));
}

function upperFirst(value) {
	if (!value) return value;
	return value.charAt(0).toUpperCase() + value.slice(1);
}

function lowerFirst(value) {
	if (!value) return value;
	return value.charAt(0).toLowerCase() + value.slice(1);
}

function splitWords(value) {
	return String(value)
		.replace(/[{}]/g, " ")
		.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean);
}

function toPascalCase(value) {
	const words = splitWords(value);
	if (words.length === 0) return "";
	return words.map((word) => upperFirst(word.toLowerCase())).join("");
}

function toCamelCase(value) {
	const pascal = toPascalCase(value);
	return lowerFirst(pascal);
}

function normalizeUrlPath(urlPath) {
	if (!urlPath) return "/";
	return urlPath.startsWith("/") ? urlPath : `/${urlPath}`;
}

function getUrlSegments(urlPath) {
	return normalizeUrlPath(urlPath).split("/").filter(Boolean);
}

function getServiceBaseName(urlPath) {
	const segments = getUrlSegments(urlPath);
	const first = segments[0] || "Api";
	const second = segments[1] || "Common";
	return `${toPascalCase(first)}${toPascalCase(second)}`;
}

function getServiceFileName(urlPath) {
	return `${getServiceBaseName(urlPath)}Service.ts`;
}

function getServiceTypesFileName(urlPath) {
	return `${getServiceBaseName(urlPath)}Types.ts`;
}

function isPathVariableSegment(segment) {
	return /^\{.+\}$/.test(segment);
}

function getPathVariableName(segment) {
	return segment.replace(/^\{/, "").replace(/\}$/, "");
}

function isPlainObject(value) {
	return value && typeof value === "object" && !Array.isArray(value);
}

function hasTypedParameterObject(parameters, key) {
	if (!isPlainObject(parameters)) return false;

	const value = parameters[key];
	if (!value) return false;

	if (value === "never") return false;

	if (isPlainObject(value)) {
		return Object.keys(value).length > 0;
	}

	return true;
}
function buildFunctionName(urlPath, method) {
	const segments = getUrlSegments(urlPath);
	const functionSegments = segments.slice(2);

	if (functionSegments.length === 0) {
		return escapeReservedIdentifier(method.toLowerCase());
	}

	const parts = functionSegments.map((segment) => {
		if (isPathVariableSegment(segment)) {
			return `By${toPascalCase(getPathVariableName(segment))}`;
		}
		return toPascalCase(segment);
	});

	return escapeReservedIdentifier(lowerFirst(parts.join("")));
}

function getSchemaRefName(ref) {
	if (!ref || typeof ref !== "string") return null;
	const matched = ref.match(/^#\/components\/schemas\/(.+)$/);
	return matched ? matched[1] : null;
}

function isValidTsIdentifier(name) {
	return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

function addTypeRef(typeRefs, refName) {
	if (refName && isValidTsIdentifier(refName)) {
		typeRefs.add(refName);
	}
}

function collectSchemaRefs(schema, typeRefs) {
	if (!schema || typeof schema !== "object") return;

	if (schema.$ref) {
		addTypeRef(typeRefs, getSchemaRefName(schema.$ref));
		return;
	}

	if (Array.isArray(schema.oneOf)) {
		schema.oneOf.forEach((item) => collectSchemaRefs(item, typeRefs));
	}
	if (Array.isArray(schema.anyOf)) {
		schema.anyOf.forEach((item) => collectSchemaRefs(item, typeRefs));
	}
	if (Array.isArray(schema.allOf)) {
		schema.allOf.forEach((item) => collectSchemaRefs(item, typeRefs));
	}

	if (schema.items) {
		collectSchemaRefs(schema.items, typeRefs);
	}

	if (
		schema.additionalProperties &&
		typeof schema.additionalProperties === "object"
	) {
		collectSchemaRefs(schema.additionalProperties, typeRefs);
	}

	if (schema.properties && typeof schema.properties === "object") {
		Object.values(schema.properties).forEach((propertySchema) => {
			collectSchemaRefs(propertySchema, typeRefs);
		});
	}
}

function applyNullable(typeString, schema) {
	if (schema && schema.nullable) {
		return `${typeString} | null`;
	}
	return typeString;
}

function schemaEnumToType(enumValues) {
	if (!Array.isArray(enumValues) || enumValues.length === 0) {
		return "string";
	}
	return enumValues.map((value) => JSON.stringify(value)).join(" | ");
}

function schemaToType(schema, typeRefs) {
	if (!schema) return "unknown";

	if (schema.$ref) {
		const refName = getSchemaRefName(schema.$ref);
		if (refName && isValidTsIdentifier(refName)) {
			addTypeRef(typeRefs, refName);
			return refName;
		}
		return "unknown";
	}

	if (Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
		return applyNullable(
			schema.oneOf
				.map((item) => schemaToType(item, typeRefs))
				.join(" | "),
			schema,
		);
	}

	if (Array.isArray(schema.anyOf) && schema.anyOf.length > 0) {
		return applyNullable(
			schema.anyOf
				.map((item) => schemaToType(item, typeRefs))
				.join(" | "),
			schema,
		);
	}

	if (Array.isArray(schema.allOf) && schema.allOf.length > 0) {
		return applyNullable(
			schema.allOf
				.map((item) => schemaToType(item, typeRefs))
				.join(" & "),
			schema,
		);
	}

	if (schema.type === "array") {
		const itemType = schemaToType(schema.items || {}, typeRefs);
		return applyNullable(`Array<${itemType}>`, schema);
	}

	if (schema.enum) {
		return applyNullable(schemaEnumToType(schema.enum), schema);
	}

	if (schema.type === "integer" || schema.type === "number") {
		return applyNullable("number", schema);
	}

	if (schema.type === "string") {
		return applyNullable("string", schema);
	}

	if (schema.type === "boolean") {
		return applyNullable("boolean", schema);
	}

	if (schema.type === "null") {
		return "null";
	}

	if (
		schema.type === "object" ||
		schema.properties ||
		schema.additionalProperties
	) {
		if (schema.additionalProperties) {
			if (schema.additionalProperties === true) {
				return applyNullable("Record<string, unknown>", schema);
			}
			return applyNullable(
				`Record<string, ${schemaToType(schema.additionalProperties, typeRefs)}>`,
				schema,
			);
		}

		const properties = schema.properties || {};
		const requiredSet = new Set(
			Array.isArray(schema.required) ? schema.required : [],
		);

		const inlineObject = `{
${Object.entries(properties)
	.map(([key, value]) => {
		const optionalMark = requiredSet.has(key) ? "" : "?";
		const propertyType = schemaToType(value, typeRefs);
		return `    ${JSON.stringify(key)}${optionalMark}: ${propertyType};`;
	})
	.join("\n")}
}`;

		return applyNullable(inlineObject, schema);
	}

	return "unknown";
}

function getPreferredContent(content) {
	if (!content || typeof content !== "object") return null;

	if (content["application/json"]) {
		return {
			contentType: "application/json",
			schema: content["application/json"].schema,
		};
	}

	const jsonLikeKey = Object.keys(content).find((key) =>
		key.includes("json"),
	);
	if (jsonLikeKey) {
		return {
			contentType: jsonLikeKey,
			schema: content[jsonLikeKey].schema,
		};
	}

	const firstKey = Object.keys(content)[0];
	if (!firstKey) return null;

	return {
		contentType: firstKey,
		schema: content[firstKey].schema,
	};
}

function getRequestBodyInfo(operation) {
	if (
		!operation ||
		!operation.requestBody ||
		!operation.requestBody.content
	) {
		return null;
	}

	const preferred = getPreferredContent(operation.requestBody.content);
	if (!preferred) return null;

	return {
		required: Boolean(operation.requestBody.required),
		contentType: preferred.contentType,
		schema: preferred.schema,
	};
}

function getComponentRefName(ref, prefix) {
	if (!ref || typeof ref !== "string") return null;
	const escapedPrefix = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
	const matched = ref.match(new RegExp(`^#/${escapedPrefix}/(.+)$`));
	return matched ? matched[1] : null;
}

function resolveParameterRef(swaggerData, parameter) {
	if (!parameter || typeof parameter !== "object") return null;

	if (!parameter.$ref) {
		return parameter;
	}

	const refName = getComponentRefName(
		parameter.$ref,
		"components/parameters",
	);
	if (!refName) return null;

	return swaggerData?.components?.parameters?.[refName] || null;
}

function getMergedParameters(swaggerData, pathItem, operation) {
	const pathParameters = Array.isArray(pathItem?.parameters)
		? pathItem.parameters
		: [];
	const operationParameters = Array.isArray(operation?.parameters)
		? operation.parameters
		: [];

	return [...pathParameters, ...operationParameters]
		.map((parameter) => resolveParameterRef(swaggerData, parameter))
		.filter(Boolean);
}

function getParametersByIn(swaggerData, pathItem, operation, parameterIn) {
	return getMergedParameters(swaggerData, pathItem, operation).filter(
		(parameter) => parameter.in === parameterIn,
	);
}

function getSuccessResponseInfo(operation) {
	if (!operation || !operation.responses) {
		return null;
	}

	const successStatusCodes = Object.keys(operation.responses)
		.filter((statusCode) => /^2\d\d$/.test(statusCode))
		.sort((a, b) => Number(a) - Number(b));

	if (successStatusCodes.length === 0) {
		return null;
	}

	for (const statusCode of successStatusCodes) {
		const response = operation.responses[statusCode];
		if (!response) continue;

		if (!response.content) {
			return {
				statusCode,
				contentType: null,
				schema: null,
			};
		}

		const preferred = getPreferredContent(response.content);
		if (preferred) {
			return {
				statusCode,
				contentType: preferred.contentType,
				schema: preferred.schema || null,
			};
		}
	}

	return null;
}

function hasPathParameters(swaggerData, urlPath, pathItem, operation) {
	if (hasTypedParameterObject(operation?.parameters, "path")) {
		return true;
	}

	if (hasTypedParameterObject(pathItem?.parameters, "path")) {
		return true;
	}

	if (
		getParametersByIn(swaggerData, pathItem, operation, "path").length > 0
	) {
		return true;
	}

	return /\{[^}]+\}/.test(urlPath);
}

function hasQueryParameters(swaggerData, pathItem, operation) {
	if (hasTypedParameterObject(operation?.parameters, "query")) {
		return true;
	}

	if (hasTypedParameterObject(pathItem?.parameters, "query")) {
		return true;
	}

	return (
		getParametersByIn(swaggerData, pathItem, operation, "query").length > 0
	);
}

function resolveBodyType({ urlPath, method, requestBodyInfo, typeRefs }) {
	if (!requestBodyInfo) return null;

	if (requestBodyInfo.schema && requestBodyInfo.schema.$ref) {
		collectSchemaRefs(requestBodyInfo.schema, typeRefs);
		return schemaToType(requestBodyInfo.schema, typeRefs);
	}

	if (requestBodyInfo.schema) {
		collectSchemaRefs(requestBodyInfo.schema, typeRefs);
		const typeFromSchema = schemaToType(requestBodyInfo.schema, typeRefs);
		if (typeFromSchema && typeFromSchema !== "unknown") {
			return typeFromSchema;
		}
	}

	return `paths['${urlPath}']['${method}']['requestBody']['content']['${requestBodyInfo.contentType}']`;
}

function resolveResponseType({ responseInfo, typeRefs }) {
	if (!responseInfo) {
		return "unknown";
	}

	if (!responseInfo.schema) {
		if (responseInfo.statusCode === "204") {
			return "void";
		}
		return "unknown";
	}

	collectSchemaRefs(responseInfo.schema, typeRefs);
	return schemaToType(responseInfo.schema, typeRefs);
}

function buildFunctionCode({
	urlPath,
	method,
	responseType,
	bodyType,
	useCallApiStream,
	hasPathParams,
	hasQueryParams,
	requestBodyRequired,
}) {
	const argEntries = [];
	const objectFields = [];

	if (hasPathParams) {
		argEntries.push(
			`path: paths['${urlPath}']['${method}']['parameters']['path']`,
		);
		objectFields.push(`     pathVariable: path,`);
	}

	if (hasQueryParams) {
		argEntries.push(
			`params: paths['${urlPath}']['${method}']['parameters']['query']`,
		);
		objectFields.push(`     queryString: params,`);
	}

	if (bodyType) {
		const bodyOptionalMark = requestBodyRequired ? "" : "?";
		argEntries.push(`body${bodyOptionalMark}: ${bodyType}`);
		objectFields.push(`     body,`);
	}

	const functionName = buildFunctionName(urlPath, method);
	const callerName = useCallApiStream ? "callApiStream" : "callApi";

	const headerLines = [];
	if (argEntries.length === 0) {
		headerLines.push(`export const ${functionName} = () => {`);
	} else {
		headerLines.push(`export const ${functionName} = ({`);
		if (hasPathParams) headerLines.push(`   path,`);
		if (hasQueryParams) headerLines.push(`  params,`);
		if (bodyType) headerLines.push(`    body,`);
		headerLines.push(`}: {`);
		argEntries.forEach((entry) => headerLines.push(`    ${entry};`));
		headerLines.push(`}) => {`);
	}

	const serviceArgumentsLines = [
		`       url: '${urlPath}',`,
		`       method: '${method}',`,
		...objectFields,
	];

	const bodyLines = [
		`   const serviceArguments: ServiceArguments<paths, '${urlPath}', '${method}', ${responseType}> = {`,
		...serviceArgumentsLines,
		`   };`,
	];

	bodyLines.push(
		``,
		`   return ${callerName}<${responseType}>(serviceArguments);`,
		`};`,
	);

	return [...headerLines, ...bodyLines].join("\n");
}

// 📌 업데이트됨: 동적으로 계산된 apiTypesImportPath를 사용하도록 변경
function generateTypeFileContent({ apiTypesImportPath, typeRefs }) {
	const sortedRefs = Array.from(typeRefs).sort((a, b) => a.localeCompare(b));

	let content = AUTO_GENERATED_COMMENT;
	content += "\n";
	content += `import type { components } from '${apiTypesImportPath}';\n`;

	if (sortedRefs.length > 0) {
		content += "\n";
		sortedRefs.forEach((typeName) => {
			content += `export type ${typeName} = components['schemas']['${typeName}'];\n\n`;
		});
	}

	return content;
}

function generateServiceFileContent({
	serviceFilePath,
	serviceTypeFilePath,
	commonServiceFilePath,
	commonTypesFilePath,
	apiTypesFilePath,
	functionBlocks,
	localTypeRefs,
	commonTypeRefs,
	usesCallApiStream,
}) {
	const imports = [];

	const pathsImportPath = getRelativeImportPath(
		serviceFilePath,
		apiTypesFilePath,
	);
	imports.push(`import type { paths } from '${pathsImportPath}';`);
	imports.push(
		`import type { ServiceArguments } from '@byeolnaerim/typed-rx-http';`,
	);

	if (localTypeRefs.size > 0) {
		const typeImportPath = getRelativeImportPath(
			serviceFilePath,
			serviceTypeFilePath,
		);
		const sortedRefs = Array.from(localTypeRefs).sort((a, b) =>
			a.localeCompare(b),
		);
		imports.push(
			`import type { ${sortedRefs.join(", ")} } from '${typeImportPath}';`,
		);
	}

	if (commonTypeRefs.size > 0) {
		const typeImportPath = getRelativeImportPath(
			serviceFilePath,
			commonTypesFilePath,
		);
		const sortedRefs = Array.from(commonTypeRefs).sort((a, b) =>
			a.localeCompare(b),
		);
		imports.push(
			`import type { ${sortedRefs.join(", ")} } from '${typeImportPath}';`,
		);
	}

	const commonServiceImportPath = getRelativeImportPath(
		serviceFilePath,
		commonServiceFilePath,
	);

	if (usesCallApiStream) {
		imports.push(
			`import { callApi, callApiStream } from '${commonServiceImportPath}';`,
		);
	} else {
		imports.push(`import { callApi } from '${commonServiceImportPath}';`);
	}

	let content = AUTO_GENERATED_COMMENT;
	content += "\n";
	content += imports.join("\n");
	content += "\n\n";
	content += functionBlocks.join("\n\n");
	content += "\n";

	return content;
}

function shouldUseCallApiStream(responseInfo) {
	if (!responseInfo || !responseInfo.contentType) return false;
	return responseInfo.contentType.includes("text/event-stream");
}

function writeFileIfChanged(filePath, nextContent) {
	const prevContent = fs.existsSync(filePath)
		? fs.readFileSync(filePath, "utf8")
		: null;

	if (prevContent === nextContent) {
		return false;
	}

	fs.writeFileSync(filePath, nextContent, "utf8");
	return true;
}

function generateSwaggerServices({
	swaggerData,
	serviceDir,
	typesDir,
	typesFile,
	commonServiceFile,
	log = console,
}) {
	if (!swaggerData || !swaggerData.paths) {
		log.warn?.(
			"No paths found in swaggerData. Skipping service generation.",
		);
		return;
	}

	ensureDirSync(serviceDir);
	ensureDirSync(typesDir);

	const apiTypesFilePath = path.resolve(typesFile);

	// 📌 변경됨: 호출부에서 전달한 경로를 그대로 절대경로로 변환합니다. (serviceDir 내부라고 가정하지 않음)
	const commonServiceFilePath = path.resolve(commonServiceFile);

	// 📌 변경됨: types 디렉토리(생성되는 타입 파일 위치)에서 apiTypesFilePath(원본 ApiTypes.d.ts)를 참조할 때의 상대 경로 계산
	const apiTypesImportPathForTypes = getRelativeImportPath(
		path.resolve(typesDir, "dummy.ts"), // 임시 파일명으로 경로 깊이 측정
		apiTypesFilePath,
	);

	const serviceMap = new Map();

	const sortedPaths = Object.keys(swaggerData.paths).sort((a, b) =>
		a.localeCompare(b),
	);

	for (const urlPath of sortedPaths) {
		const pathItem = swaggerData.paths[urlPath];
		if (!pathItem || typeof pathItem !== "object") continue;

		const methods = Object.keys(pathItem)
			.filter((method) =>
				[
					"get",
					"post",
					"put",
					"delete",
					"patch",
					"options",
					"head",
				].includes(method.toLowerCase()),
			)
			.sort((a, b) => a.localeCompare(b));

		for (const method of methods) {
			const operation = pathItem[method];
			if (!operation || typeof operation !== "object") continue;

			const serviceFileName = getServiceFileName(urlPath);
			const serviceBaseName = getServiceBaseName(urlPath);
			const serviceTypesFileName = getServiceTypesFileName(urlPath);

			if (!serviceMap.has(serviceFileName)) {
				serviceMap.set(serviceFileName, {
					serviceBaseName,
					serviceFileName,
					serviceTypeFileName: serviceTypesFileName,
					functionNameSet: new Set(),
					functionBlocks: [],
					typeRefs: new Set(),
					usesCallApiStream: false,
				});
			}

			const serviceInfo = serviceMap.get(serviceFileName);
			const functionName = buildFunctionName(urlPath, method);

			if (serviceInfo.functionNameSet.has(functionName)) {
				log.warn?.(
					`[generateSwaggerServices] skipped duplicated function name "${functionName}" in ${serviceFileName} (${method.toUpperCase()} ${urlPath})`,
				);
				continue;
			}

			const requestBodyInfo = getRequestBodyInfo(operation);
			const responseInfo = getSuccessResponseInfo(operation);

			const bodyType = resolveBodyType({
				urlPath,
				method,
				requestBodyInfo,
				typeRefs: serviceInfo.typeRefs,
			});

			const responseType = resolveResponseType({
				responseInfo,
				typeRefs: serviceInfo.typeRefs,
			});

			const useCallApiStream = shouldUseCallApiStream(responseInfo);
			if (useCallApiStream) {
				serviceInfo.usesCallApiStream = true;
			}

			const hasPathParams = hasPathParameters(
				swaggerData,
				urlPath,
				pathItem,
				operation,
			);
			const hasQueryParams = hasQueryParameters(
				swaggerData,
				pathItem,
				operation,
			);

			const functionCode = buildFunctionCode({
				urlPath,
				method,
				responseType,
				bodyType,
				useCallApiStream,
				hasPathParams,
				hasQueryParams,
				requestBodyRequired: Boolean(requestBodyInfo?.required),
			});

			serviceInfo.functionNameSet.add(functionName);
			serviceInfo.functionBlocks.push(functionCode);
		}
	}

	const globalTypeUsage = new Map();
	for (const [serviceFileName, serviceInfo] of serviceMap.entries()) {
		for (const typeRef of serviceInfo.typeRefs) {
			if (!globalTypeUsage.has(typeRef)) {
				globalTypeUsage.set(typeRef, new Set());
			}
			globalTypeUsage.get(typeRef).add(serviceFileName);
		}
	}

	const commonTypesSet = new Set();
	for (const [typeRef, servicesUsingIt] of globalTypeUsage.entries()) {
		if (servicesUsingIt.size > 1) {
			commonTypesSet.add(typeRef);
		}
	}

	const commonTypesFileName = "ApiCommonsTypes.ts";
	const commonTypesFilePath = path.resolve(typesDir, commonTypesFileName);

	if (commonTypesSet.size > 0) {
		const commonTypesContent = generateTypeFileContent({
			apiTypesImportPath: apiTypesImportPathForTypes, // 📌 업데이트됨
			typeRefs: commonTypesSet,
		});
		const isCommonWritten = writeFileIfChanged(
			commonTypesFilePath,
			commonTypesContent,
		);
		if (isCommonWritten) {
			log.log?.(`Generated common types file: ${commonTypesFilePath}`);
		}
	} else if (fs.existsSync(commonTypesFilePath)) {
		fs.unlinkSync(commonTypesFilePath);
	}

	for (const serviceInfo of serviceMap.values()) {
		const serviceFilePath = path.resolve(
			serviceDir,
			serviceInfo.serviceFileName,
		);
		const serviceTypeFilePath = path.resolve(
			typesDir,
			serviceInfo.serviceTypeFileName,
		);

		const localTypesSet = new Set();
		const serviceCommonTypesSet = new Set();

		for (const typeRef of serviceInfo.typeRefs) {
			if (commonTypesSet.has(typeRef)) {
				serviceCommonTypesSet.add(typeRef);
			} else {
				localTypesSet.add(typeRef);
			}
		}

		let isTypeWritten = false;

		if (localTypesSet.size > 0) {
			const typeFileContent = generateTypeFileContent({
				apiTypesImportPath: apiTypesImportPathForTypes, // 📌 업데이트됨
				typeRefs: localTypesSet,
			});
			isTypeWritten = writeFileIfChanged(
				serviceTypeFilePath,
				typeFileContent,
			);
		} else {
			if (fs.existsSync(serviceTypeFilePath)) {
				fs.unlinkSync(serviceTypeFilePath);
			}
		}

		const serviceFileContent = generateServiceFileContent({
			serviceFilePath,
			serviceTypeFilePath,
			commonServiceFilePath,
			commonTypesFilePath,
			apiTypesFilePath,
			functionBlocks: serviceInfo.functionBlocks,
			localTypeRefs: localTypesSet,
			commonTypeRefs: serviceCommonTypesSet,
			usesCallApiStream: serviceInfo.usesCallApiStream,
		});

		const isServiceWritten = writeFileIfChanged(
			serviceFilePath,
			serviceFileContent,
		);

		if (isTypeWritten) {
			log.log?.(`Generated types file: ${serviceTypeFilePath}`);
		}
		if (isServiceWritten) {
			log.log?.(`Generated service file: ${serviceFilePath}`);
		}
	}
}

const RESERVED_TS_IDENTIFIER_NAMES = new Set([
	"abstract",
	"any",
	"as",
	"asserts",
	"async",
	"await",
	"bigint",
	"boolean",
	"break",
	"case",
	"catch",
	"class",
	"const",
	"constructor",
	"continue",
	"debugger",
	"declare",
	"default",
	"delete",
	"do",
	"else",
	"enum",
	"export",
	"extends",
	"false",
	"finally",
	"for",
	"from",
	"function",
	// 'get',
	"global",
	"if",
	"implements",
	"import",
	"in",
	"infer",
	"instanceof",
	"interface",
	"is",
	"keyof",
	"let",
	"module",
	"namespace",
	"never",
	"new",
	"null",
	"number",
	"object",
	"of",
	"package",
	"private",
	"protected",
	"public",
	"readonly",
	"require",
	"return",
	"satisfies",
	// 'set',
	"static",
	"string",
	"super",
	"switch",
	"symbol",
	"this",
	"throw",
	"true",
	"try",
	"type",
	"typeof",
	"undefined",
	"unique",
	"unknown",
	"var",
	"void",
	"while",
	"with",
	"yield",
]);

function escapeReservedIdentifier(name) {
	if (RESERVED_TS_IDENTIFIER_NAMES.has(name)) {
		return `_${name}`;
	}

	return name;
}

module.exports = {
	generateSwaggerServices,
	getServiceBaseName,
	getServiceFileName,
	getServiceTypesFileName,
	buildFunctionName,
};
