const fs = require("fs");
const path = require("path");

const AUTO_GENERATED_COMMENT =
	"// This file is auto-generated by generateAsyncApiRSocketXxxService.js. Do not edit.\n";

function ensureDirSync(dirPath) {
	if (!fs.existsSync(dirPath)) {
		fs.mkdirSync(dirPath, { recursive: true });
	}
}

function stripExtension(fileName) {
	return fileName.replace(/\.d\.ts$/i, "").replace(/\.ts$/i, "");
}

function normalizeImportPath(filePath) {
	let normalized = filePath.replace(/\\/g, "/");
	if (!normalized.startsWith(".")) {
		normalized = "./" + normalized;
	}
	return normalized;
}

function getRelativeImportPath(fromFilePath, toFilePath) {
	const fromDir = path.dirname(fromFilePath);
	const rel = path.relative(fromDir, toFilePath);
	return normalizeImportPath(stripExtension(rel));
}

function upperFirst(value) {
	if (!value) return value;
	return value.charAt(0).toUpperCase() + value.slice(1);
}

function lowerFirst(value) {
	if (!value) return value;
	return value.charAt(0).toLowerCase() + value.slice(1);
}

function splitWords(value) {
	return String(value)
		.replace(/[{}]/g, " ")
		.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean);
}

function toPascalCase(value) {
	const words = splitWords(value);
	if (words.length === 0) return "";
	return words.map((word) => upperFirst(word.toLowerCase())).join("");
}

function toCamelCase(value) {
	const pascal = toPascalCase(value);
	return lowerFirst(pascal);
}

function isValidTsIdentifier(name) {
	return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

const RESERVED_TS_IDENTIFIER_NAMES = new Set([
	"abstract",
	"any",
	"as",
	"asserts",
	"async",
	"await",
	"bigint",
	"boolean",
	"break",
	"case",
	"catch",
	"class",
	"const",
	"constructor",
	"continue",
	"debugger",
	"declare",
	"default",
	"delete",
	"do",
	"else",
	"enum",
	"export",
	"extends",
	"false",
	"finally",
	"for",
	"from",
	"function",
	"global",
	"if",
	"implements",
	"import",
	"in",
	"infer",
	"instanceof",
	"interface",
	"is",
	"keyof",
	"let",
	"module",
	"namespace",
	"never",
	"new",
	"null",
	"number",
	"object",
	"of",
	"package",
	"private",
	"protected",
	"public",
	"readonly",
	"require",
	"return",
	"satisfies",
	"static",
	"string",
	"super",
	"switch",
	"symbol",
	"this",
	"throw",
	"true",
	"try",
	"type",
	"typeof",
	"undefined",
	"unique",
	"unknown",
	"var",
	"void",
	"while",
	"with",
	"yield",
]);

function escapeReservedIdentifier(name) {
	if (RESERVED_TS_IDENTIFIER_NAMES.has(name)) {
		return `_${name}`;
	}
	return name;
}

function getRefName(ref) {
	return ref ? ref.split("/").pop() : null;
}

function resolveRef(ref, asyncapiData) {
	if (!ref || !ref.startsWith("#/")) {
		return null;
	}

	return ref
		.slice(2)
		.split("/")
		.reduce((current, token) => {
			if (current == null) {
				return null;
			}

			return current[token.replace(/~1/g, "/").replace(/~0/g, "~")];
		}, asyncapiData);
}

function getMessage(messageRefOrObject, asyncapiData) {
	if (!messageRefOrObject) return null;
	if (messageRefOrObject.$ref) {
		return resolveRef(messageRefOrObject.$ref, asyncapiData);
	}
	if (Array.isArray(messageRefOrObject.oneOf) && messageRefOrObject.oneOf.length > 0) {
		return getMessage(messageRefOrObject.oneOf[0], asyncapiData);
	}
	return messageRefOrObject;
}

function getMessageRSocketMeta(messageRefOrObject, asyncapiData) {
	const message = getMessage(messageRefOrObject, asyncapiData);
	return message?.["x-rsocket"] || {};
}

function getControllerSimpleName(controller) {
	if (!controller) return null;
	return String(controller).split(".").pop().split("$").pop();
}

function getServiceBaseName(entry) {
	const controllerSimpleName = getControllerSimpleName(entry.controller);
	if (controllerSimpleName) {
		const normalized = controllerSimpleName
			.replace(/RSocketController$/i, "")
			.replace(/Controller$/i, "");
		const baseName = toPascalCase(normalized);
		return `${baseName || "Api"}RSocket`;
	}

	const destinationBase = String(entry.destination).split(".").slice(0, 2).join(".");
	return `${toPascalCase(destinationBase) || "Api"}RSocket`;
}

function getServiceFileName(entry) {
	return `${getServiceBaseName(entry)}Service.ts`;
}

function getServiceTypesFileName(entry) {
	return `${getServiceBaseName(entry)}Types.ts`;
}

function getFunctionName(entry) {
	const methodName = entry.method ? String(entry.method) : "";
	if (methodName) {
		return escapeReservedIdentifier(lowerFirst(toPascalCase(methodName)));
	}

	return escapeReservedIdentifier(toCamelCase(entry.destination) || "request");
}

function getTypeAliasBase(functionName) {
	return toPascalCase(functionName) || "Request";
}

function isPlainObject(value) {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}

function getMessagePayload(messageRefOrObject, asyncapiData) {
	const message = getMessage(messageRefOrObject, asyncapiData);
	return message?.payload || null;
}

function isEmptySchema(schema, asyncapiData) {
	if (!schema) return true;

	if (schema.$ref) {
		return isEmptySchema(resolveRef(schema.$ref, asyncapiData), asyncapiData);
	}

	if (Array.isArray(schema.allOf)) {
		const meaningfulItems = schema.allOf.filter(
			(item) => isPlainObject(item) && !item["x-paramName"],
		);
		return meaningfulItems.length === 0 || meaningfulItems.every((item) => isEmptySchema(item, asyncapiData));
	}

	if (Array.isArray(schema.oneOf) || Array.isArray(schema.anyOf)) {
		return false;
	}

	if (schema.type === "object" || schema.properties || schema.additionalProperties !== undefined) {
		return Object.keys(schema.properties || {}).length === 0 && !schema.additionalProperties;
	}

	return false;
}

function getInteraction({ publishMessage, subscribeMessage, channel, asyncapiData }) {
	const publishMeta = getMessageRSocketMeta(publishMessage, asyncapiData);
	const responseMeta = getMessageRSocketMeta(subscribeMessage, asyncapiData);
	const isStream = Boolean(channel.subscribe?.["x-rsocket"]?.stream);
	return publishMeta.interaction || responseMeta.interaction || (isStream ? "requestStream" : "requestResponse");
}

function getRSocketEntries(asyncapiData) {
	const channels = asyncapiData.channels || {};

	return Object.entries(channels)
		.map(([destination, channel]) => {
			const publishMessage = channel.publish?.message;
			const subscribeMessage = channel.subscribe?.message;
			const publishMeta = getMessageRSocketMeta(publishMessage, asyncapiData);
			const responseMeta = getMessageRSocketMeta(subscribeMessage, asyncapiData);
			const channelMeta = channel["x-rsocket"] || {};
			const routeMeta = Array.isArray(channelMeta.routes) ? channelMeta.routes[0] || {} : {};
			const interaction = getInteraction({ publishMessage, subscribeMessage, channel, asyncapiData });
			const requestPayload = getMessagePayload(publishMessage, asyncapiData);

			return {
				destination,
				interaction,
				fireAndForget: Boolean(publishMeta.fireAndForget || responseMeta.fireAndForget),
				controller: publishMeta.controller || responseMeta.controller || routeMeta.controller,
				method: publishMeta.method || responseMeta.method || routeMeta.method,
				requestOptional: isEmptySchema(requestPayload, asyncapiData),
			};
		})
		.sort((a, b) => {
			const serviceCompare = getServiceFileName(a).localeCompare(getServiceFileName(b));
			if (serviceCompare !== 0) return serviceCompare;
			return getFunctionName(a).localeCompare(getFunctionName(b));
		});
}

function buildFunctionCode(entry) {
	const functionName = getFunctionName(entry);
	const typeAliasBase = getTypeAliasBase(functionName);
	const requestType = `${typeAliasBase}Request`;
	const responseType = `${typeAliasBase}Response`;
	const callerName = entry.interaction === "requestStream" ? "callRSocketStream" : "callRSocketMono";
	const destinationLiteral = JSON.stringify(entry.destination);

	if (entry.requestOptional) {
		return `export const ${functionName} = () => {\n\treturn ${callerName}<${destinationLiteral}>(${destinationLiteral});\n};`;
	}

	return `export const ${functionName} = ({\n\tbody,\n}: {\n\tbody: ${requestType};\n}) => {\n\treturn ${callerName}<${destinationLiteral}>(${destinationLiteral}, body);\n};`;
}

function buildTypesFileContent({ entries, asyncApiTypesImportPath }) {
	let content = AUTO_GENERATED_COMMENT;
	content += "\n";
	content += `import type { AsyncApiRSocketRequest, AsyncApiRSocketResponse } from '${asyncApiTypesImportPath}';\n\n`;

	entries.forEach((entry) => {
		const functionName = getFunctionName(entry);
		const typeAliasBase = getTypeAliasBase(functionName);
		content += `export type ${typeAliasBase}Request = AsyncApiRSocketRequest<${JSON.stringify(entry.destination)}>;\n`;
		content += `export type ${typeAliasBase}Response = AsyncApiRSocketResponse<${JSON.stringify(entry.destination)}>;\n\n`;
	});

	return content;
}

function buildServiceFileContent({ entries, serviceFilePath, serviceTypeFilePath, commonRSocketServiceFilePath }) {
	const serviceTypesImportPath = getRelativeImportPath(serviceFilePath, serviceTypeFilePath);
	const commonRSocketServiceImportPath = getRelativeImportPath(serviceFilePath, commonRSocketServiceFilePath);
	const typeNames = [];
	let usesMono = false;
	let usesStream = false;

	entries.forEach((entry) => {
		const functionName = getFunctionName(entry);
		const typeAliasBase = getTypeAliasBase(functionName);
		if (!entry.requestOptional) {
			typeNames.push(`${typeAliasBase}Request`);
		}
		if (entry.interaction === "requestStream") {
			usesStream = true;
		} else {
			usesMono = true;
		}
	});

	const uniqueTypeNames = Array.from(new Set(typeNames)).sort((a, b) => a.localeCompare(b));
	const callImports = [];
	if (usesMono) callImports.push("callRSocketMono");
	if (usesStream) callImports.push("callRSocketStream");

	let content = AUTO_GENERATED_COMMENT;
	content += "\n";
	if (uniqueTypeNames.length > 0) {
		content += `import type { ${uniqueTypeNames.join(", ")} } from '${serviceTypesImportPath}';\n`;
	}
	content += `import { ${callImports.join(", ")} } from '${commonRSocketServiceImportPath}';\n\n`;
	content += entries.map(buildFunctionCode).join("\n\n");
	content += "\n";

	return content;
}

function writeFileIfChanged(filePath, nextContent) {
	const prevContent = fs.existsSync(filePath)
		? fs.readFileSync(filePath, "utf8")
		: null;

	if (prevContent === nextContent) {
		return false;
	}

	fs.writeFileSync(filePath, nextContent, "utf8");
	return true;
}

function generateAsyncApiRSocketServices({
	asyncapiData,
	serviceDir,
	typesDir,
	typesFile,
	commonRSocketServiceFile,
	log = console,
}) {
	if (!asyncapiData || !asyncapiData.channels) {
		log.warn?.("No channels found in asyncapiData. Skipping RSocket service generation.");
		return;
	}

	ensureDirSync(serviceDir);
	ensureDirSync(typesDir);

	const entries = getRSocketEntries(asyncapiData);
	const serviceMap = new Map();

	entries.forEach((entry) => {
		const serviceFileName = getServiceFileName(entry);
		if (!serviceMap.has(serviceFileName)) {
			serviceMap.set(serviceFileName, []);
		}
		serviceMap.get(serviceFileName).push(entry);
	});

	const asyncApiTypesFilePath = path.resolve(typesFile);
	const commonRSocketServiceFilePath = path.resolve(commonRSocketServiceFile);

	for (const [serviceFileName, serviceEntries] of serviceMap.entries()) {
		const serviceFilePath = path.resolve(serviceDir, serviceFileName);
		const serviceTypeFilePath = path.resolve(typesDir, getServiceTypesFileName(serviceEntries[0]));
		const asyncApiTypesImportPath = getRelativeImportPath(serviceTypeFilePath, asyncApiTypesFilePath);

		const typesContent = buildTypesFileContent({
			entries: serviceEntries,
			asyncApiTypesImportPath,
		});
		const serviceContent = buildServiceFileContent({
			entries: serviceEntries,
			serviceFilePath,
			serviceTypeFilePath,
			commonRSocketServiceFilePath,
		});

		const isTypeWritten = writeFileIfChanged(serviceTypeFilePath, typesContent);
		const isServiceWritten = writeFileIfChanged(serviceFilePath, serviceContent);

		if (isTypeWritten) {
			log.log?.(`Generated RSocket types file: ${serviceTypeFilePath}`);
		}
		if (isServiceWritten) {
			log.log?.(`Generated RSocket service file: ${serviceFilePath}`);
		}
	}
}

module.exports = {
	generateAsyncApiRSocketServices,
	getRSocketEntries,
	getServiceBaseName,
	getServiceFileName,
	getServiceTypesFileName,
	getFunctionName,
};
